version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
environment:
  GitHubKey:
    secure: oQiZ+bhbS5xA+tjgAIVgKTbmDjFzwjLTBEcp24QYMEcNZillCY5LyfuxwMtbbYB+uIets6jrO5B1pHhuCQlHp4J1TQ67PAlKR+/rzJiKhCnCWqAUwgkQpThmX2daD5IR
  NuGetApiKey:
    secure: rPSzJcM4Eg8bvjQW++ROY8rluvZyT7YjzmVgnFjNLYwU1WZ/kT1weSz0eherkZzY
install:
- ps: . .\ci\Install.ps1
build_script:
- ps: . .\ci\GitHub.ps1
- ps: . .\ci\Build.ps1
test_script:
- ps: . .\ci\Tests.ps1
- ps: . .\ci\GitHub.ps1
deploy_script:
- ps: . .\ci\Deploy.ps1

skip_commits:
  message: /AppVeyor validate.*|Merge branch 'main' of.*|Update docs.*/

only_commits:
  files:
    - J81.NSToolkit.*/**/*
