name: AppVentiX PowerShell Module
on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  pester-test:
    name: validation and push
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          clean: true
      - name: Install requirements
        shell: pwsh
        run: |
          .\ci\Install.ps1
      - name: Perform tests
        shell: pwsh
        run: |
          .\ci\Tests.ps1
      - name: Publish module
        shell: pwsh
        env:
          NugetApiKeyDev: ${{ secrets.PSGALLERYTEST }}
          NugetApiKey: ${{ secrets.PSGALLERY }}
        run: |
          .\ci\Build.ps1
